### ISSUE TITLE
Detect out-of-date or Debug plugin assemblies

### ISSUE THREAD

**Issue by jrinker03** [CubeSuite/ModdersAssistant#3]
Because we are human, it is too easy to forget to copy the latest Release build to the Mod Files folder prior to starting Prepare Upload.

Ideally the tool would recognize that the current assembly is a Debug (non-optimized) assembly.  See [this technique](https://dave-black.blogspot.com/2011/12/how-to-tell-if-assembly-is-debug-or.html) as a suggestion for how to do this.

Since the tool probably knows where the source code is, it should be able to tell if the assembly in the bin/release folder matches the assembly its been asked to zip for upload.

In either case where there is a potential issue, the modder should be warned.

**Comment by CubeSuite** [comment]
Just FYI, MA grabs the plugin's .dll file from the game folder every 5 seconds, so it always has the latest version in the Mod Files folder. 

Latest version added a step to the 'Prepare Upload' process that does a release build and copies it to Mod Files.

**Comment by jrinker03** [comment]
Fantastic!
